version: '3.4'

services:
  mydb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'makeEat'
      MYSQL_ROOT_PASSWORD: 'pp'
    ports:
      - 3333:3306

  make-eat:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000